### ISSUE TITLE
Refresh button - history

### ISSUE THREAD

**Issue by GuestHelix** [HelixNetwork/nautilus#40]
We need some "call for action" next to the refresh button, this way it may not be clear what is it for.

Maybe just text: "Click to refresh"
or
Highlight or info pop up in the wallet with the Sync button ( Like making it flash maybe and information pop up telling to press sync if you are awaiting transaction in your history)

macOS Mojave (Version 10.14.6)

**Comment by sachushaji** [comment]
Have added the click to refresh text near the refresh button. V1.1.0
