### ISSUE TITLE
Overlapping in the History section

### ISSUE THREAD

**Issue by GuestHelix** [HelixNetwork/nautilus#44]
In the History section, the address and amount of HLX field is overlapping

![Screenshot 2019-10-03 at 20 21 35](https://user-images.githubusercontent.com/38652218/66207203-76033680-e6b2-11e9-817a-ede9011cdf16.png)

macOS Mojave (Version 10.14.6)

**Comment by sachushaji** [comment]
It should be fixed in 1.1.0
