### ISSUE TITLE
Cannot spent from multiple addresses

### ISSUE THREAD

**Issue by dzhelezov** [HelixNetwork/nautilus#65]
To reproduce (on testnet):
- Go to Settings -> View Addresses
- Start with a fresh account
- Top up 5 unused address with the faucet bot @helix_explorer_test_bot on Telegram (10k each)
- Try to spend 50k in a single transaction

Expected behaviour
- A transaction is spent OR a meaningful message (i.e. "Please break down your transfers into smaller transactions") is shown

Actual behavior
- Unspecified error

**Comment by sachushaji** [comment]
Most probably duplicates the issue #68

**Comment by sachushaji** [comment]
Closed with #72
