### ISSUE TITLE
Account balance is not updated

### ISSUE THREAD

**Issue by dzhelezov** [HelixNetwork/nautilus#66]
To reproduce (on testnet):
- Top up an account with multiple requests to the faucet bot @helix_explorer_test_bot within a short period of time
- Wait until the transactions are confirmed

Expected behavior:
- When the transactions are confirmed, the total balance is updated

Actual behavior:
- The transactions are shown as "RECIEVED" but the account balance is updated only after a while

**Comment by sachushaji** [comment]
Fixed with #72 , The delay is still present and have been mitigated to an extend. The delay between balance updates and inclusion state update fixed from protocol side will solve this.
