### ISSUE TITLE
Cannot find inputs with provided limit

### ISSUE THREAD

**Issue by oliverfn** [HelixNetwork/nautilus#68]
## Steps to Reproduce

1. Send 1337 mHLX to a sub-account which already contained 2578 HLX 
2. Transfer is confirmed, the sub-account now contains 1337002578 HLX
3. Try to spend 2579 HLX from this sub-account to an arbitrary address
4. Transfer Error: Something went wrong while sending your transfer. Please try again. (according to error log: Cannot find inputs with provided limits)

## Context

* Version: v1.1.0
* Operating System: MacOS 10.14.6

## Failure Logs

No specific information in devtools. 
Error log:
```
16/01/2020 12:45 Cannot find inputs with provided limit.
```

**Comment by sachushaji** [comment]
Fixed with #72
