### ISSUE TITLE
The balance is not updated upon account change

### ISSUE THREAD

**Issue by dzhelezov** [HelixNetwork/nautilus#70]
To reproduce:
-- create two accounts
-- Top up
-- Switch between the accounts

Expected behavior:
-- The actual balances is displayed

Actual Behavior:
-- Upon changing e.g. from Account 1 to Account 2 the balance of Account 1 is still displayed.

Wallet version: v 1.1.0

**Comment by sachushaji** [comment]
Fixed with #72
